# Generated by Django 4.1.3 on 2022-11-27 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='finch',
            name='finch_image',
            field=models.ImageField(default=1, upload_to='upload/'),
            preserve_default=False,
        ),
    ]
